from functools import lru_cache
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    app_name: str = "Agric Procurement Platform"
    environment: str = "development"
    api_prefix: str = "/api/v1"

    database_url: str = "postgresql+asyncpg://agric:agric@localhost:5432/agric"
    db_ssl_required: bool = False

    redis_url: str = "redis://localhost:6379/0"

    # Notification delivery transport:
    #   "in_process" (default) - a background asyncio task in the API process.
    #                            Needs no second service, which is what lets the
    #                            whole app run on one free-tier web service.
    #   "redis"                - arq queue consumed by a separate worker process
    #                            (docker-compose). Use when you have somewhere to
    #                            run that worker.
    # Either way notifications are never sent inline, on the request path.
    queue_backend: str = "in_process"

    jwt_secret: str = "change-me-in-production"
    jwt_algorithm: str = "HS256"
    access_token_expire_minutes: int = 30
    refresh_token_expire_days: int = 14

    cors_origins: list[str] = ["http://localhost:5173"]

    # SameSite policy for the refresh-token cookie. "lax" is right when the API
    # and the frontend share an origin (local dev). The hosted deployment serves
    # them from two different hostnames, so the browser treats every API call as
    # cross-site and drops a Lax cookie, breaking silent refresh. render.yaml sets
    # this to "none" for that reason; "none" always implies Secure.
    refresh_cookie_samesite: str = "lax"

    # Storage: "local" or "s3"
    storage_backend: str = "local"
    local_storage_path: str = "storage/uploads"
    local_storage_public_url: str = "/static/uploads"
    s3_bucket: str = ""
    s3_region: str = "eu-west-1"
    # Any S3-compatible endpoint works here, not just AWS - Supabase Storage,
    # Backblaze B2, Cloudflare R2, a local MinIO. Leave the whole S3 block blank
    # to keep files on local disk.
    s3_endpoint_url: str = ""
    # Named S3_* rather than AWS_* on purpose: some hosts inject AWS_ACCESS_KEY_ID
    # into the environment themselves, and pydantic reads env vars
    # case-insensitively, so fields with those names would silently pick up
    # credentials that were never meant for this app.
    s3_access_key_id: str = ""
    s3_secret_access_key: str = ""

    # Max accepted upload size, rejected with a clear 413 rather than by whatever
    # proxy sits in front of the app with an opaque error.
    max_upload_size_mb: float = 4.0

    # Email: "console" or "smtp"
    email_backend: str = "console"
    email_from: str = "no-reply@agric.example"
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_username: str = ""
    smtp_password: str = ""

    # Paystack
    paystack_secret_key: str = ""
    paystack_public_key: str = ""
    paystack_base_url: str = "https://api.paystack.co"

    frontend_url: str = "http://localhost:5173"

    # First-admin bootstrap, consumed only by app/seed_handler.py. /auth/register
    # deliberately only ever creates customers, so a deployed environment needs
    # this one-time step to have an administrator at all. render.yaml sets these,
    # with the password generated by the platform.
    # NOT a .local/.test address: those are RFC 6761 special-use names, which
    # EmailStr rejects - so a seeded admin with one could never log in, because
    # LoginRequest would 422 before the password was even checked. .example is
    # reserved-but-accepted, so it works as an obvious placeholder. Set this to a
    # real address if you want password-reset email to reach you.
    seed_admin_email: str = "admin@agric.example"
    seed_admin_password: str = ""
    seed_admin_phone: str = "+2348000000000"
    seed_demo_data: bool = True

    delivery_fee: float = 1000.0
    service_fee_percent: float = 2.5


@lru_cache
def get_settings() -> Settings:
    return Settings()
